# Generated by Django 4.1.3 on 2022-12-05 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration_portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('leader_email', models.EmailField(max_length=100)),
                ('leader_profilephoto_url', models.CharField(max_length=150)),
                ('team_profilephoto', models.ImageField(blank=True, null=True, upload_to=registration_portal.models.create_path)),
                ('team_name', models.CharField(max_length=100)),
                ('team_member_profilephoto', models.ImageField(blank=True, null=True, upload_to=registration_portal.models.create_path)),
                ('team_member_name', models.CharField(max_length=100)),
                ('team_member_email', models.EmailField(max_length=100)),
                ('payment_completed', models.BooleanField(default=False)),
                ('registration_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('client_email', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('S', 'Successful'), ('F', 'Failed')], default='F', max_length=1)),
                ('razor_pay_order_id', models.CharField(default='Old', max_length=100, primary_key=True, serialize=False)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_description', models.CharField(blank=True, max_length=100, null=True)),
                ('error_reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
