# Generated by Django 4.1.3 on 2022-12-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_member_profilephoto',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_profilephoto',
        ),
    ]
