# Generated by Django 4.1.3 on 2022-11-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leader',
        ),
    ]
