# Generated by Django 4.1.3 on 2022-12-01 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('registration_portal', '0002_delete_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('leader_email', models.EmailField(max_length=100)),
                ('leader_profilephoto_url', models.CharField(max_length=150)),
                ('team_name', models.CharField(max_length=100)),
                ('team_member_one', models.CharField(max_length=100)),
                ('team_member_two', models.CharField(max_length=100)),
            ],
        ),
    ]
