# Generated by Django 4.1.3 on 2022-12-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_portal', '0005_transaction_error_code_transaction_error_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('S', 'Successful'), ('F', 'Failed')], default=False, max_length=1),
        ),
    ]
