# Generated by Django 4.1.3 on 2022-12-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_portal', '0006_alter_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='razor_pay_order_id',
            field=models.CharField(default='Old', max_length=100, primary_key=True, serialize=False),
        ),
    ]
