# Generated by Django 4.1.3 on 2022-12-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_portal', '0008_remove_transaction_error_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='client',
            new_name='client_email',
        ),
    ]
