# Generated by Django 4.1.3 on 2022-12-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_portal', '0009_rename_client_transaction_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
